# Generated by Django 2.0.6 on 2021-08-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='fk_producto',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fk_producto',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
        migrations.DeleteModel(
            name='sell',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
