# Generated by Django 2.0.6 on 2021-08-25 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_auto_20210825_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='disponible',
            fields=[
                ('pk_disponible', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('pk_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_de_venta', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('fk_disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.disponible')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_de_dulce',
            fields=[
                ('pk_tipo_de_dulce', models.AutoField(primary_key=True, serialize=False)),
                ('sabor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('pk_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=50)),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_tipo_de_dulce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tipo_de_dulce'),
        ),
    ]
