# Generated by Django 2.0.6 on 2021-09-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210908_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_de_dulce',
            name='image2',
            field=models.URLField(default='https://i.postimg.cc/KYcsSYWN/Gomitas-agridulces.jpg', max_length=800),
        ),
    ]
