# Generated by Django 2.0.6 on 2021-09-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210908_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_de_dulce',
            old_name='image2',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='tipo_de_dulce',
            name='image1',
        ),
    ]
