# Generated by Django 2.0.6 on 2021-09-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210908_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_de_dulce',
            name='image',
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.URLField(default='https://i.postimg.cc/zGWwMR1F/Gomitas-agridulces.jpg', max_length=800),
        ),
    ]
