# Generated by Django 2.0.6 on 2021-09-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20210908_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.URLField(default='https://i.postimg.cc/SxTpy4DR/nodisponible.png', max_length=800),
        ),
    ]
