# Generated by Django 2.0.6 on 2021-09-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20210908_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponible',
            options={'ordering': ['cantidad'], 'verbose_name': 'disponible', 'verbose_name_plural': 'disponibles'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='tipo_de_dulce',
            options={'ordering': ['sabor'], 'verbose_name': 'tipo_de_dulce', 'verbose_name_plural': 'tipo_de_dulces'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['cantidad'], 'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
    ]
